package(default_visibility = ["//visibility:public"])

java_binary(
    name = "headers",
    srcs = glob(["*.java"]),
    resources = glob(["*.txt"]),
    main_class = "tools.checks.headers.HeadersChecker",
)
