package(default_visibility = ["//visibility:public"])

java_binary(
    name = "headers",
    srcs = ["HeadersChecker.java"],
    main_class = "tools.checks.headers.HeadersChecker",
    resources = glob(["*.txt"]),
)
